/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.votaciones.vista;

import com.votaciones.controlador.ControladorBroker;
import com.votaciones.ProductoDTO;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Jaret
 */
public class FrmVotacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmVotacion
     */
    private transient ControladorBroker ctrlVotaciones = null;
    private static final String FONT = "Microsoft Yi Baiti";
    
    public FrmVotacion(ControladorBroker ctrlBroker) {
        initComponents();
        this.ctrlVotaciones = ctrlBroker;
        cagarContenidoVotos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelVotaciones = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        jLabel1.setFont(new java.awt.Font(FONT, 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VOTACIONES");

        javax.swing.GroupLayout panelVotacionesLayout = new javax.swing.GroupLayout(panelVotaciones);
        panelVotaciones.setLayout(panelVotacionesLayout);
        panelVotacionesLayout.setHorizontalGroup(
            panelVotacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        panelVotacionesLayout.setVerticalGroup(
            panelVotacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(panelVotaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(panelVotaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelVotaciones;
    // End of variables declaration//GEN-END:variables

    private void cagarContenidoVotos() {
        
        Map<ProductoDTO, JLabel> lblVotosMap = new HashMap<>();
        
        JPanel panelContenido = new JPanel(new GridBagLayout());

        GridBagConstraints posCelda = new GridBagConstraints();
        posCelda.insets = new Insets(20, 20, 20, 20);
        posCelda.fill = GridBagConstraints.HORIZONTAL;
        posCelda.gridy = 0;
        
        List<ProductoDTO> listaProductos = ctrlVotaciones.getProductos();

        for (ProductoDTO producto : listaProductos) {  
            JLabel lblNombre = new JLabel(producto.getNombre());
            lblNombre.setFont(new Font(FONT, Font.BOLD, 24));

            JLabel lblVotos = new JLabel("Votos: " + producto.getVotos());
            lblVotos.setFont(new Font(FONT, Font.BOLD, 18));

            lblVotosMap.put(producto, lblVotos);

            JButton btnVotar = new JButton("Votar " + producto.getNombre());
            btnVotar.addActionListener(e -> {
                ctrlVotaciones.votarProducto(producto);
                lblVotos.setText("Votos: " + producto.getVotos());
            });

            posCelda.gridx = 0; 
            panelContenido.add(lblNombre, posCelda);
            
            posCelda.gridx = 1;
            panelContenido.add(lblVotos, posCelda);
            
            posCelda.gridx = 2;
            panelContenido.add(btnVotar, posCelda);

            posCelda.gridy++;
        }

        JScrollPane scroll = new JScrollPane(panelContenido);
        
        panelVotaciones.removeAll();
        panelVotaciones.setLayout(new BorderLayout());
        panelVotaciones.add(scroll, BorderLayout.CENTER);
        panelVotaciones.revalidate();
        panelVotaciones.repaint();
    }
}
