/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.votaciones.vista;

import com.votaciones.controlador.ControladorBroker;
import com.votaciones.modelo.ControladorBrokerListener;
import com.votaciones.ProductoDTO;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Jaret
 */
public class FrmVotacion extends javax.swing.JFrame implements ControladorBrokerListener {

    /**
     * Creates new form FrmVotacion
     */
    private transient ControladorBroker ctrlVotaciones = null;
    private static final String FONT = "Microsoft Yi Baiti";
    private Map<String, JLabel> lblVotosMap = new HashMap<>();
    
    public FrmVotacion(ControladorBroker ctrlBroker) {
        initComponents();
        this.ctrlVotaciones = ctrlBroker;
        ctrlBroker.addListener(this);
        cagarContenidoVotos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelVotaciones = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuPastel = new javax.swing.JMenuItem();
        menuBarras = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuBitacora = new javax.swing.JMenuItem();
        menuServicios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VOTACIONES");

        javax.swing.GroupLayout panelVotacionesLayout = new javax.swing.GroupLayout(panelVotaciones);
        panelVotaciones.setLayout(panelVotacionesLayout);
        panelVotacionesLayout.setHorizontalGroup(
            panelVotacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        panelVotacionesLayout.setVerticalGroup(
            panelVotacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(panelVotaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(panelVotaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jMenu3.setText("Gráficas");

        menuPastel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuPastel.setText("Pastel");
        menuPastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPastelActionPerformed(evt);
            }
        });
        jMenu3.add(menuPastel);

        menuBarras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuBarras.setText("Barras");
        menuBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarrasActionPerformed(evt);
            }
        });
        jMenu3.add(menuBarras);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");

        menuBitacora.setText("Bitácora");
        menuBitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBitacoraActionPerformed(evt);
            }
        });
        jMenu4.add(menuBitacora);

        menuServicios.setText("Servicios");
        menuServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiciosActionPerformed(evt);
            }
        });
        jMenu4.add(menuServicios);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPastelActionPerformed
        // TODO add your handling code here:
        FrmGraficaPastel frmGraficaPastel = new FrmGraficaPastel(ctrlVotaciones);
        
        frmGraficaPastel.setLocation(600, 100);
        frmGraficaPastel.setVisible(true);
    }//GEN-LAST:event_menuPastelActionPerformed

    private void menuBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarrasActionPerformed
        // TODO add your handling code here:
        FrmGraficaBarras frmGraficaBarras = new FrmGraficaBarras(ctrlVotaciones);
        frmGraficaBarras.setLocation(600, 450);
        frmGraficaBarras.setVisible(true);
    }//GEN-LAST:event_menuBarrasActionPerformed

    private void menuBitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBitacoraActionPerformed
        // TODO add your handling code here:
        FrmBitacora frmBitacora = new FrmBitacora(ctrlVotaciones);
        frmBitacora.setLocationRelativeTo(null);
        frmBitacora.setVisible(true);
    }//GEN-LAST:event_menuBitacoraActionPerformed

    private void menuServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiciosActionPerformed
        // TODO add your handling code here:
        FrmServicios frmServicios = new FrmServicios(ctrlVotaciones);
        frmServicios.setLocationRelativeTo(null);
        frmServicios.setVisible(true);
    }//GEN-LAST:event_menuServiciosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem menuBarras;
    private javax.swing.JMenuItem menuBitacora;
    private javax.swing.JMenuItem menuPastel;
    private javax.swing.JMenuItem menuServicios;
    private javax.swing.JPanel panelVotaciones;
    // End of variables declaration//GEN-END:variables

    private void cagarContenidoVotos() {
        
        JPanel panelContenido = new JPanel(new GridBagLayout());

        GridBagConstraints posCelda = new GridBagConstraints();
        posCelda.insets = new Insets(20, 20, 20, 20);
        posCelda.fill = GridBagConstraints.HORIZONTAL;
        posCelda.gridy = 0;
        
        List<ProductoDTO> listaProductos = ctrlVotaciones.getProductos();

        for (ProductoDTO producto : listaProductos) {  
            JLabel lblNombre = new JLabel(producto.getNombre());
            lblNombre.setFont(new Font(FONT, Font.BOLD, 24));

            JLabel lblVotos = new JLabel("Votos: " + producto.getVotos());
            lblVotos.setFont(new Font(FONT, Font.BOLD, 18));

            lblVotosMap.put(producto.getNombre(), lblVotos);

            JButton btnVotar = new JButton("Votar " + producto.getNombre());
            btnVotar.addActionListener(e -> {
                ctrlVotaciones.votarProducto(producto);
                lblVotos.setText("Votos: " + producto.getVotos());
            });

            posCelda.gridx = 0; 
            panelContenido.add(lblNombre, posCelda);
            
            posCelda.gridx = 1;
            panelContenido.add(lblVotos, posCelda);
            
            posCelda.gridx = 2;
            panelContenido.add(btnVotar, posCelda);

            posCelda.gridy++;
        }

        JScrollPane scroll = new JScrollPane(panelContenido);
        
        panelVotaciones.removeAll();
        panelVotaciones.setLayout(new BorderLayout());
        panelVotaciones.add(scroll, BorderLayout.CENTER);
        panelVotaciones.revalidate();
        panelVotaciones.repaint();
    }

    @Override
    public void onCambioVotos(List<ProductoDTO> productos) {
        for (ProductoDTO producto : productos) {
            JLabel lbl = lblVotosMap.get(producto.getNombre());
            if (lbl != null) {
                lbl.setText("Votos: " + producto.getVotos());
            }
        }
        panelVotaciones.revalidate();
        panelVotaciones.repaint();
    }
}
